apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-repo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-repo
  template:
    metadata:
      labels:
        app: saas-repo
    spec:
      containers:
        - name: saas-repo
          image: localhost:5001/java-demo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
