apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
        - name: java-demo
          image: localhost:5001/java-demo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
